# Generated by Django 5.0.2 on 2024-02-19 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basqa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basqa',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basqa',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='basqa.category'),
        ),
        migrations.AddField(
            model_name='basqa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='basqa.tagpost'),
        ),
        migrations.AddIndex(
            model_name='basqa',
            index=models.Index(fields=['time_create'], name='basqa_basqa_time_cr_3926f0_idx'),
        ),
    ]
